export const navigationData = [
  {
    title: 'Calendar',
    href: '/calendar',
  },
  {
    title: 'Activities',
    href: '/activities',
    submenu: [
      { title: '2 Gun Defense', href: '/activities/2-gun-defense' },
      { title: '22 Rimfire Benchrest 100-200 yard', href: '/activities/22-rimfire-benchrest' },
      { title: '600-Yard Prone/Bench', href: '/activities/600-yard-prone-bench' },
      { title: 'Archery', href: '/activities/archery' },
      { title: 'Black Powder Cartridge, Pistol Caliber Lever Rifle, Smallbore Silhouette', href: '/activities/black-powder-cartridge' },
      { title: 'Cowboy Action Shooting', href: '/activities/cowboy-action-shooting' },
      { title: 'Everyday Carry (EDC)', href: '/activities/everyday-carry' },
      { title: 'International Defensive Pistol Association (IDPA)', href: '/activities/idpa' },
      { title: 'Junior Air Pistol/Air Rifle', href: '/activities/junior-air-pistol-rifle' },
      { title: 'Junior Smallbore', href: '/activities/junior-smallbore' },
      { title: 'Multi-Gun', href: '/activities/multi-gun' },
      { title: 'Muzzle Loader', href: '/activities/muzzle-loader' },
      { title: 'Police Pistol Combat', href: '/activities/police-pistol-combat' },
      { title: 'Practical Rifle', href: '/activities/practical-rifle' },
      { title: 'Precision Pistol (formerly Conventional Pistol)', href: '/activities/precision-pistol' },
      { title: 'Rimfire Sporter', href: '/activities/rimfire-sporter' },
      { title: 'Senior Smallbore', href: '/activities/senior-smallbore' },
      { title: 'Skeet', href: '/activities/skeet' },
      { title: 'Speed Steel', href: '/activities/speed-steel' },
      { title: 'Sporter Highpower', href: '/activities/sporter-highpower' },
      { title: 'Sporting Clays', href: '/activities/sporting-clays' },
      { title: 'Sunday Clays', href: '/activities/sunday-clays' },
      { title: 'Tactical', href: '/activities/tactical' },
      { title: 'Trap', href: '/activities/trap' },
      { title: 'USPSA', href: '/activities/uspsa' },
      { title: 'Vintage Military Rifle/Pistol', href: '/activities/vintage-military' },
    ],
  },
  {
    title: 'Facilities',
    href: '/facilities',
    submenu: [
      { title: 'Action Range', href: '/facilities/action-range' },
      { title: 'Archery Ranges', href: '/facilities/archery-ranges' },
      { title: 'Black Powder / Silhouette / Rimfire Range', href: '/facilities/black-powder-silhouette-rimfire' },
      { title: 'Conventional Pistol Range', href: '/facilities/conventional-pistol-range' },
      { title: 'General Purpose Range', href: '/facilities/general-purpose-range' },
      { title: 'Indoor Range', href: '/facilities/indoor-range' },
      { title: 'Shotgun Fields', href: '/facilities/shotgun-fields' },
      { title: 'Short Distance Pistol Range', href: '/facilities/short-distance-pistol-range' },
      { title: '200 – 300 Yard Range', href: '/facilities/200-300-yard-range' },
      { title: '600 Yard Range', href: '/facilities/600-yard-range' },
    ],
  },
  {
    title: 'Training',
    href: '/training',
    submenu: [
      { title: 'ONLINE COURSE REGISTRATION', href: '/training/online-registration' },
      {
        title: 'Certification',
        submenu: [
          { title: 'Action Range Certification Process', href: '/training/certification/action-range-process' },
          { title: 'Action Range Certification', href: '/training/certification/action-range' },
          { title: 'Practical Rifle Orientation', href: '/training/certification/practical-rifle-orientation' },
        ],
      },
      {
        title: 'Pistol Training',
        submenu: [
          { title: 'Action Shooting Fundamentals', href: '/training/pistol/action-shooting-fundamentals' },
          { title: 'Concealed Carry-Multi-State', href: '/training/pistol/concealed-carry' },
        ],
      },
      { title: 'Rifle Training', href: '/training/rifle' },
      { title: 'Shotgun Key & Fundamentals', href: '/training/shotgun-fundamentals' },
      { title: 'Oregon Hunters Education', href: '/training/oregon-hunters-education' },
      { title: 'Youth Series Training: Introduction to Rifle', href: '/training/youth-series-rifle' },
    ],
  },
  {
    title: 'About the Club',
    href: '/about',
    submenu: [
      { title: 'TCGC Tour', href: '/about/tour' },
      { title: 'How to Join the Club', href: '/about/join' },
      { title: 'Hours and Directions', href: '/about/hours-directions' },
      { title: 'Membership', href: '/about/membership' },
      { title: 'Member support', href: '/about/member-support' },
      { title: 'Safety and Range Rules', href: '/about/safety-rules' },
      { title: 'Proshop/FFL', href: '/about/proshop' },
      { title: 'Contact us', href: '/about/contact' },
    ],
  },
  {
    title: 'Members Only',
    href: '/members',
    submenu: [
      { title: 'Member Portal', href: '/members/portal' },
      { title: 'Meetings', href: '/members/meetings' },
      { title: 'Newsletter', href: '/members/newsletter' },
      { title: 'Officials', href: '/members/officials' },
      { title: 'Official Documents', href: '/members/documents' },
      { title: 'Policies and Procedures', href: '/members/policies' },
      { title: 'Guest Waiver Release Form', href: '/members/guest-waiver' },
      { title: 'FFL Firearm Transfer Form', href: '/members/ffl-transfer' },
    ],
  },
];
